source "https://rubygems.org"
gem "rspec"
gem "page-object"
gem "faker"
gem "data_magic"
gem "require_all"
gem "cucumber", "1.3.20"
gem "pretty_face"
gem "rspec_pretty_report"
gem "rouge"
gem "rspec-legacy_formatters"
gem "fig_newton"
