storm:
  username: tim.sheng@student.com
  password: abc20052614
  base_url: https://oslqa:m2WackNUHbAqHz51@storm-frontend-cn-draft.dandythrust.com
  row_base_url: https://oslqa:m2WackNUHbAqHz51@storm-frontend-draft.dandythrust.com
  property_path: /uk/london/tufnell-house
booking:
  base_url: https://oslqa:m2WackNUHbAqHz51@bookings.stage.overseasstudentliving.com
  username: tim.sheng
  password: 111111
