storm:
  username: tim.sheng@student.com
  password: abc20052614
  base_url: https://oslqa:m2WackNUHbAqHz51@storm-frontend-cn.dandythrust.com
  row_base_url: https://oslqa:m2WackNUHbAqHz51@storm-frontend.dandythrust.com
  application_path: /my-account/application-details
  property_path: /uk/london/tufnell-house
  # property_path: /au/sydney/uws-village-hawkesbury-campus
  # property_path: /uk/manchester/weston-court
booking:
  base_url: https://oslqa:m2WackNUHbAqHz51@bookings.stage.overseasstudentliving.com
  username: tim.sheng
  password: 111111

page_path:
  homepage: /
  propertypage: /uk/london/tufnell-house
  applicationdetailspage: /my-account/application-details
